### ISSUE TITLE
Curious on what differs with /system/bin/wpa_supplicant_real

### ISSUE THREAD

**Issue by RoundSparrow** [moosd/NetworkGhost#1]
How is this binary different from the included one?

I'm trying to track down a wpa_cli for android 5... if you know of one, please let me know.

**Comment by souramoo** [comment]
During setup, android's own `wpa_supplicant` is renamed to `wpa_supplicant_real`. It creates a script `wpa_supplicant` which acts as a wrapper for the original binary, just changes the mac address to what we want it to be every time before wpa_supplicant is launched for real.

There is a `wpa_cli` binary included with cyanogenmod, but you will need to point it towards the socket file for wpa_supplicant. The location is passed to wpa_supplicant in the command line arguments. You can play around with dumping the command line arguments from the wrapper script to some temporary location whenever it starts up to figure out where the socket file is and get wpa_cli to connect to it.
